version: "3.8"

services: 
  nginx:
    image: nginx:stable-perl
    ports: 
      - '80:80'
    volumes: 
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
    
    depends_on:
      - php
    
  php:
    build: 
      context: ./www
      dockerfile: php.dockerfile
    
    ports: 
      - '9000:9000'
    
    volumes:
      - ./www:/var/www/html      # for automisation 
      - ./mysql/mysql_sock:/var/run/mysqld 
    



  mysql:
    platform: linux/x86_64
    image: mysql:8.0.31-debian

    ports: 
      - '33267:3306'

    volumes:
      - ./mysql/data:/var/lib/mysql        # for automisation 
      - ./mysql/conf:/etc/mysql/conf.d 
      - ./mysql/mysql_sock:/var/run/mysqld 

    env_file:
      - ./mysql/.env

    depends_on:
      - php

  vuejs:

    build:
      context: ./vuejs
      dockerfile: vue.dockerfile

    volumes:
      - ./vuejs/src:/app/src

    ports: 
      - '8080:80'
    
    stdin_open: true    
    tty: true 
  
    depends_on:
      - nginx
      - php
      - mysql
    



    
